main/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm


app_name = 'main'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^filter/(?P<filter>[-\w]+)/$', views.IndexView.as_view(), name='filtered-recipes'),
    url(r'^(?P<pk>\d+)/$', views.RecipeDetail.as_view(), name='get_recipe'),
    url(r'^edit/(?P<pk>\d+)/$', views.RecipeUpdate.as_view(), name='edit_recipe'),
    url(r'^add', views.RecipeCreate.as_view(), name='add_recipe'),
    url(r'^login/$', auth_views.LoginView.as_view(form_class = LoginForm,
                                                 template_name = "main/login.html"),name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup')
]

recipes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('main/', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace='main:index')),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Ingredient(models.Model):
    name = models.CharField('Название', max_length=20)

    def __str__(self):
        return self.name


class Writer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Recipe(models.Model):
    MEAL_CHOICES = (('all', 'ALL'),('breakfast', 'Breakfasts'),
                    ('main-dish', 'Main Dishes'), ('desserts', 'Desserts'),
                    ('salads', 'Salads'), ('soups', 'Soups'))
    name = models.CharField('Name', max_length=200)
    description = models.TextField('Description', max_length=2000)
    meal = models.CharField('Meal', choices=MEAL_CHOICES, blank=True,
                            max_length=10)
    pub_date = models.DateField(auto_now_add=True)
    writer = models.ForeignKey(Writer, on_delete=models.CASCADE, blank=True,
                               null=True)
    ingredient = models.ManyToManyField(Ingredient)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:get_recipe', kwargs={'pk': self.pk})

    class Meta:
        permissions = (
            ('edit_recipe', 'Edit recipe'),
        )


@receiver(post_save, sender=User)
def update_user_writer(sender, instance, created, **kwargs):
    if created:
        Writer.objects.create(user=instance)
    instance.writer.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Recipe, Ingredient


class RecipeForm(forms.ModelForm):
    meal = forms.ChoiceField(required=True, choices=Recipe.MEAL_CHOICES)

    class Meta:
        model = Recipe
        exclude = ['pub_date', 'writer']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'ingredient' in self.data:
            ingredients = self.data.getlist('ingredient')
            list_of_ingredient_ids = []
            for ingredient in ingredients:
                if ingredient.isdigit():
                    list_of_ingredient_ids.append(ingredient)
                else:
                    new_ingredient = Ingredient.objects.create(name=ingredient)
                    list_of_ingredient_ids.append(str(new_ingredient.id))
                self.ingredients = kwargs.pop('url', list_of_ingredient_ids)
            super(RecipeForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        valid = super(RecipeForm, self).is_valid()
        if self.errors.get("ingredient"):
            if len(Ingredient.objects.filter(id__in = self.ingredients)) == \
                    len(self.ingredients):
                del self.errors["ingredient"]
        if len(self.errors) == 0:
            self.cleaned_data["ingredient"] = Ingredient.objects.filter(id__in = self.ingredients)
            return True
        else:
            return False


class IngredientForm():
    class Meta:
        model = Ingredient


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))


class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )

main/views.py
from django.views import generic
from .models import Recipe, Writer
from .forms import RecipeForm, SignUpForm
from django.shortcuts import redirect
from guardian.shortcuts import assign_perm


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'recipes_list'

    def get_queryset(self, **kwargs):
        filter_val = self.kwargs.get('filter')
        if filter_val:
            if filter_val == 'all':
                new_context = Recipe.objects.all()
            else:
                new_context = Recipe.objects.filter(meal=filter_val)
        else:
            new_context = Recipe.objects.all()
        return new_context


class RecipeUpdate(generic.UpdateView):
    model = Recipe
    form_class = RecipeForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        user = self.request.user
        if user.has_perm('edit_recipe', obj):
            return super(RecipeUpdate, self).dispatch(request, *args, **kwargs)
        else:
            return redirect(obj)


class RecipeDetail(generic.DetailView):
    model = Recipe


class RecipeCreate(generic.CreateView):
    model = Recipe
    form_class = RecipeForm

    def form_valid(self, form):
        recipe = form.save(commit=False)
        user = self.request.user
        recipe.writer = Writer.objects.get(user=user.id)
        recipe.save()
        assign_perm('edit_recipe', user, recipe)
        print(user.has_perm('edit_recipe', recipe))
        return super().form_valid(form)


class SignUpView(generic.FormView):
    template_name = 'main/signup.html'
    form_class = SignUpForm
    success_url = '/login'

    def form_valid(self, form):
        user = form.save()
        return super(SignUpView, self).form_valid(form)

main/templates/main/base.html
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <title>{% if title %}{{ title }}{% else %}Рецепты{% endif %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.css' %}"/>
    <link href="{% static 'select2/dist/css/select2.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="{% static 'main/img/favicon.ico' %}"/>
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'select2/dist/js/select2.js' %}"></script>
    <script src="{% static 'main/js/main.js' %}"></script>
</head>
<body>
<div class="row header">
    <div class="col-3">
        {% if user.is_authenticated %}
            <a class="general-button" href={% url 'main:add_recipe' %}>ADD
                RECIPE</a>
            <a href={% url 'main:logout' %}>Log Out</a>
        {% else %}
            <a id="login" href={% url 'main:login' %}>Log In</a>
            <a id="signup" href={% url 'main:signup' %}>Sign Up</a>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-3 meal-categories">
        {% if meals %}
            <ol>
            {% for meal in meals %}
                <li>
                    <a href={% url 'main:filtered-recipes' filter=meal.0 %}>
                        {{ meal.1 }}
                    </a>
                </li>
            {% endfor %}
            </ol>
        {% endif %}
    </div>
    {% block pagecontent %}
    {% endblock %}
</div>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}{% endblock %}

<body>
{% block pagecontent %}
{% load guardian_tags %}

    <div class="col-8 list">
        {% if recipes_list %}
            <ol class="">
            {% for recipe in recipes_list %}
                {% get_obj_perms request.user for recipe as "recipe_perms" %}

                <li>
                    <a href={% url 'main:get_recipe' recipe.id %}>
                    {{ recipe.name }}</a>

                    {% if "edit_recipe" in recipe_perms %}
                        <a id="edit-icon" href={%url 'main:edit_recipe' recipe.id %}>
                            edit</a>
                    {% endif %}
                </li>
            {% endfor %}
            </ol>
        {% else %}
            <h3>No recipes are available.</h3>
        {% endif %}
    </div>
{% endblock %}
</body>

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block title %}Login{% endblock %}
<body>
{% block pagecontent %}
<div class="login">
    <form id="login-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="submit" type="submit" value="LOGIN" />
    </form>
</div>
{% endblock %}
</body>

main/templates/main/recipe_detail.html
{% extends 'main/base.html' %}
{% block title %}{% endblock %}
<body>
{% block pagecontent %}
<div class="col-8 recipe-detail">
    <div class="content">
        <h1>{{ object.name }}</h1>
        <hr/>
        <h4>Meal:</h4><p>{{ object.get_meal_display }}</p><hr/>
        <h4>Ingredients:</h4>
        {% if object.ingredient.all %}
            <ol>
            {% for ingredient in object.ingredient.all %}
                <li>{{ ingredient }}</li>
            {% endfor %}
            </ol>
        {% else %}
            <h3>There is no ingredients</h3>
        {% endif %}
        <h4>Description:</h4><p>{{ object.description | linebreaks}}</p><hr/>
    </div>
</div>
{% endblock %}
</body>

main/templates/main/recipe_form.html
{% extends 'main/base.html' %}
{% block title %}{% endblock %}
<body>
{% block pagecontent %}
    <div class="col-8 recipe-info">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="submit" type="submit" value="Save" />
        </form>
    </div>
{% endblock %}
</body>

main/templates/main/signup.html
{% extends 'main/base.html' %}
{% block title %}Sign Up{% endblock %}
<body>
{% block pagecontent %}
<div class="login">
    <form id="login-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="submit" type="submit" value="SIGN UP" />
    </form>
</div>
{% endblock %}
</body>